return {
    "lewis6991/gitsigns.nvim",
    event = { "BufReadPre", "BufNewFile" },
    keys = {
        { "]c",         ":Gitsigns next_hunk<CR>",                 desc = "Next hunk" },
        { "[c",         ":Gitsigns prev_hunk<CR>",                 desc = "Prev hunk" },
        { "<leader>hs", ":Gitsigns stage_hunk<CR>",                desc = "Stage hunk" },
        { "<leader>hr", ":Gitsigns reset_hunk<CR>",                desc = "Reset hunk" },
        { "<leader>hS", ":Gitsigns stage_buffer<CR>",              desc = "Stage buffer" },
        { "<leader>hu", ":Gitsigns undo_stage_hunk<CR>",           desc = "Undo stage hunk" },
        { "<leader>hR", ":Gitsigns reset_buffer<CR>",              desc = "Reset buffer" },
        { "<leader>hp", ":Gitsigns preview_hunk<CR>",              desc = "Preview hunk" },
        { "<leader>hb", ":Gitsigns blame_line<CR>",                desc = "Blame line" },
        { "<leader>tb", ":Gitsigns toggle_current_line_blame<CR>", desc = "Toggle blame line" },
        { "<leader>hd", ":Gitsigns diffthis<CR>",                  desc = "Diff this" },
        { "<leader>hD", ":Gitsigns diffthis '~'<CR>",              desc = "Diff this ~" },
        { "<leader>td", ":Gitsigns toggle_deleted<CR>",            desc = "Toggle deleted" },
    },
    opts = {
        signs = {
            add = { text = "+" },
            change = { text = "~" },
            delete = { text = "_" },
            topdelete = { text = "‾" },
            changedelete = { text = "~" },
            untracked = { text = "┆" },
        },
        signcolumn = false,
        numhl = true,
        linehl = false,
        word_diff = false,
        watch_gitdir = {
            follow_files = true,
        },
        attach_to_untracked = true,
        current_line_blame = false,
        current_line_blame_opts = {
            virt_text = true,
            virt_text_pos = "eol",
            delay = 1000,
            ignore_whitespace = false,
        },
        current_line_blame_formatter = "<author>, <author_time:%Y-%m-%d> - <summary>",
        sign_priority = 6,
        update_debounce = 100,
        status_formatter = nil,
        max_file_length = 40000,
        preview_config = {
            border = "single",
            style = "minimal",
            relative = "cursor",
            row = 0,
            col = 1,
        },
    },
}
